USE ROLE HOL1;
USE WAREHOUSE HOL1_WH;
USE SCHEMA HOL1_DB.HOL1_SCHEMA;

-- Upload data files to stage
-- If using Vscode, make sure you open the HOL1 folder when executing below 4 commands
-- If using Snowsight you can manually upload the files to the stage
PUT file://data/application_record.csv @DATA_STAGE;  
PUT file://data/credit_record.csv @DATA_STAGE;
PUT file://data/new_application_record.csv @DATA_STAGE;
PUT file://data/new_credit_record.csv @DATA_STAGE;

CREATE OR REPLACE STAGE DATA_STAGE FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
CREATE TABLE IF NOT EXISTS HOL1_DB.HOL1_SCHEMA.APPLICATION_RECORD (
    ID INTEGER,
    CODE_GENDER VARCHAR(10),
    FLAG_OWN_CAR VARCHAR(1),
    FLAG_OWN_REALTY VARCHAR(1),
    CNT_CHILDREN INTEGER,
    AMT_INCOME_TOTAL DECIMAL(18, 2),
    NAME_INCOME_TYPE VARCHAR(50),
    NAME_EDUCATION_TYPE VARCHAR(50),
    NAME_FAMILY_STATUS VARCHAR(50),
    NAME_HOUSING_TYPE VARCHAR(50),
    DAYS_BIRTH INTEGER,
    DAYS_EMPLOYED INTEGER,
    FLAG_MOBIL INTEGER,
    FLAG_WORK_PHONE INTEGER,
    FLAG_PHONE INTEGER,
    FLAG_EMAIL INTEGER,
    OCCUPATION_TYPE VARCHAR(50),
    CNT_FAM_MEMBERS INTEGER
);
COPY INTO HOL1_DB.HOL1_SCHEMA.APPLICATION_RECORD FROM @DATA_STAGE/application_record.csv.gz FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
CREATE TABLE IF NOT EXISTS HOL1_DB.HOL1_SCHEMA.CREDIT_RECORD (
    ID INTEGER,
    MONTHS_BALANCE INTEGER,
    STATUS VARCHAR(1)
);
COPY INTO HOL1_DB.HOL1_SCHEMA.CREDIT_RECORD FROM @DATA_STAGE/credit_record.csv.gz FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

CREATE TABLE IF NOT EXISTS HOL1_DB.HOL1_SCHEMA.NEW_APPLICATION_RECORD LIKE APPLICATION_RECORD;
CREATE TABLE IF NOT EXISTS HOL1_DB.HOL1_SCHEMA.NEW_CREDIT_RECORD LIKE CREDIT_RECORD;
COPY INTO HOL1_DB.HOL1_SCHEMA.NEW_APPLICATION_RECORD FROM @DATA_STAGE/new_application_record.csv.gz FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
COPY INTO HOL1_DB.HOL1_SCHEMA.NEW_CREDIT_RECORD FROM @DATA_STAGE/new_credit_record.csv.gz FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
-- After this step, you should have the following tables in HOL1_DB.HOL1_SCHEMA:
-- APPLICATION_RECORD, CREDIT_RECORD, NEW_APPLICATION_RECORD, NEW_CREDIT_RECORD
-- make sure to view them in snowsight that they are not empty


-- create a table to store prediction history for Streamlit app
CREATE OR REPLACE TABLE HOL1_DB.HOL1_SCHEMA.PREDICTION_RESULTS (
    ID STRING,
    PREDICTION INT,
    MODEL_VERSION STRING
);